"""initial_migration

Revision ID: 6267fa1bdd6e
Revises: 
Create Date: 2026-07-17 17:00:19.066549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6267fa1bdd6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('farmer_notes', sa.Text(), nullable=True),
    sa.Column('predicted_disease', sa.String(length=150), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    # ### end Alembic commands ###
